---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos72

suites:
  - name: default
    run_list:
      - recipe[audit-test::default]
    verifier:
      #this is the folder we're sharing between kitchen/compliance audits
      inspec_tests:
        - files/tests/smoke/default
    attributes:
